### ISSUE TITLE
Directory never loads

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/old-all-about-olaf#11]
Stalkernet never loads.

**Comment by hawkrives** [comment]
It appears that m.stolaf.edu is down.

**Comment by drewvolz** [comment]
I sent Beach a friendly email last night alerting him of the problem with the mobile sub domain, just in the case it slipped past his radar. We will see if he gets back to us.

**Comment by hawkrives** [comment]
:+1:

**Comment by drewvolz** [comment]
He was unaware of this. He reported the mobile site was managed and hosted elsewhere, and he'll let who is responsible know.

**Comment by hawkrives** [comment]
It appears to be back up.
