### ISSUE TITLE
Schedule details screens should highlight the current day of the week

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/old-all-about-olaf#7]
Main use case: last night, I kept thinking that it was Sunday, when it was actually Saturday. 

If "Saturday" had been highlighted on the TableView, I would have been saved from my own silliness. 

![IMG_0295.PNG](http://southerly-uploads.s3.amazonaws.com/dfebe0089db4a43b62219da0e730fc60a8e073e6.png)

**Comment by drewvolz** [comment]
Yes, it really should be more intuitive and think for the user. It's on the to-do, now.
